version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - '.github/workflows'
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - '*'