name: build wheels
on:
  push:
  pull_request:

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-20.04, manylinux_2_27_x86_64]
    name: building ${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    env:
      HAVE_TEST_ID: ${{ secrets.ZITI_TEST_IDENTITY != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Python Tools
        run: python -m pip install -U pip setuptools wheel auditwheel

      - name: Get Ziti SDK C
        run: |
          set -x
          python tools/get_zitilib.py

      - name: Run Integration Tests
        if: ${{ env.HAVE_TEXT_ID == 'true' }}
        env:
          ZITI_TEST_IDENTITY: ${{ secrets.ZITI_TEST_IDENTITY }}
          ZITI_IDENTITIES: id.json
        run: |
          echo "${ZITI_TEST_IDENTITY}" > "${ZITI_IDENTITIES}"
          python -m unittest tests/ziti_tests.py

      - name: Build wheels
        run: |
          set -x
          pip wheel . -w ./wheelhouse
          ls -l ./wheelhouse
          auditwheel show ./wheelhouse/*
          auditwheel repair --plat=${{ matrix.buildplat[1] }} ./wheelhouse/*

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
