name: build wheels
on:
  push:
  pull_request:

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        python: ["cp38"]
        buildplat:
          - [ubuntu-20.04, manylinux_x86_64]
    name: building wheel for r ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Used to push the built wheels
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Get Ziti SDK C
        run: |
          set -x
          python tools/get_zitilib.py

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl


